export interface ExportOptions {
  output: string;
  context?: string;
  taskType?: string;
  projectName?: string;
  timestamp?: Date;
}

export interface MarkdownOptions extends ExportOptions {
  includeMeta?: boolean;
  includeTimestamp?: boolean;
  codeBlockLanguage?: string;
}

export interface PdfOptions extends ExportOptions {
  pageSize?: 'a4' | 'letter';
  orientation?: 'portrait' | 'landscape';
  margins?: { top: number; right: number; bottom: number; left: number };
  headerText?: string;
  footerText?: string;
}

export interface JsonExportOptions extends ExportOptions {
  pretty?: boolean;
  includeVersion?: boolean;
}

export interface CsvRow {
  [key: string]: string | number | undefined;
}

function sanitizeMarkdown(str: string): string {
  return str
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;');
}

function generateMarkdownContent(options: MarkdownOptions): string {
  const { output, context, taskType, projectName, timestamp, includeMeta = true, includeTimestamp = true, codeBlockLanguage = '' } = options;
  const date = timestamp || new Date();

  let markdown = '';

  if (includeMeta) {
    markdown += `# QA Copilot BY ssrjkk Report\n\n`;
    
    if (includeTimestamp) {
      markdown += `**Date:** ${date.toLocaleString()}\n\n`;
    }

    if (projectName) {
      markdown += `**Project:** ${sanitizeMarkdown(projectName)}\n\n`;
    }

    if (taskType) {
      markdown += `**Task Type:** ${sanitizeMarkdown(taskType)}\n\n`;
    }

    markdown += `---\n\n`;
  }

  if (context) {
    markdown += `## Context\n\n${sanitizeMarkdown(context)}\n\n---\n\n`;
  }

  markdown += `## Generated Output\n\n`;
  markdown += `\`\`\`${codeBlockLanguage}\n${output}\n\`\`\`\n\n`;

  markdown += `---\n\n`;
  markdown += `*Generated by QA Copilot BY ssrjkk - AI-Powered QA Assistant*\n`;

  return markdown;
}

async function generatePdfBlob(options: PdfOptions): Promise<Blob> {
  const { default: jsPDF } = await import('jspdf');
  const { output, context, taskType, projectName, timestamp, pageSize = 'a4', orientation = 'portrait', margins = { top: 20, right: 20, bottom: 20, left: 20 }, headerText = 'QA Copilot BY ssrjkk Report', footerText = 'Generated by QA Copilot BY ssrjkk - AI-Powered QA Assistant' } = options;
  const date = timestamp || new Date();

  const doc = new jsPDF({ orientation, unit: 'mm', format: pageSize });
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const contentWidth = pageWidth - margins.left - margins.right;
  let yPos = margins.top;

  const checkPageBreak = (neededSpace: number) => {
    if (yPos + neededSpace > pageHeight - margins.bottom) {
      doc.addPage();
      yPos = margins.top;
      return true;
    }
    return false;
  };

  doc.setFontSize(20);
  doc.setTextColor(124, 58, 237);
  doc.text(headerText, margins.left, yPos);
  yPos += 10;

  doc.setFontSize(10);
  doc.setTextColor(100);
  doc.text(`Date: ${date.toLocaleString()}`, margins.left, yPos);
  yPos += 6;

  if (projectName) {
    doc.text(`Project: ${projectName}`, margins.left, yPos);
    yPos += 6;
  }

  if (taskType) {
    doc.text(`Task Type: ${taskType}`, margins.left, yPos);
    yPos += 6;
  }

  yPos += 4;
  doc.setDrawColor(200);
  doc.line(margins.left, yPos, pageWidth - margins.right, yPos);
  yPos += 8;

  if (context) {
    checkPageBreak(30);
    doc.setFontSize(14);
    doc.setTextColor(76, 29, 149);
    doc.text('Context', margins.left, yPos);
    yPos += 7;

    doc.setFontSize(10);
    doc.setTextColor(60);
    const contextLines = doc.splitTextToSize(context, contentWidth);
    for (const line of contextLines) {
      checkPageBreak(6);
      doc.text(line, margins.left, yPos);
      yPos += 5;
    }
    yPos += 8;
  }

  checkPageBreak(30);
  doc.setFontSize(14);
  doc.setTextColor(76, 29, 149);
  doc.text('Generated Output', margins.left, yPos);
  yPos += 7;

  doc.setFontSize(10);
  doc.setTextColor(60);
  const outputLines = doc.splitTextToSize(output, contentWidth);
  for (const line of outputLines) {
    checkPageBreak(6);
    doc.text(line, margins.left, yPos);
    yPos += 5;
  }

  doc.setFontSize(8);
  doc.setTextColor(150);
  const footerY = pageHeight - margins.bottom + 10;
  doc.text(footerText, margins.left, footerY > 0 ? footerY : 10);

  return doc.output('blob');
}

export const exportUtils = {
  async toMarkdown(options: MarkdownOptions): Promise<Blob> {
    const content = generateMarkdownContent(options);
    return new Blob([content], { type: 'text/markdown;charset=utf-8' });
  },

  async toPdf(options: PdfOptions): Promise<Blob> {
    return generatePdfBlob(options);
  },

  async toJson(options: JsonExportOptions): Promise<Blob> {
    const data: Record<string, unknown> = {
      timestamp: (options.timestamp || new Date()).toISOString(),
      project: options.projectName,
      taskType: options.taskType,
      context: options.context,
      output: options.output
    };
    
    if (options.includeVersion) {
      data.version = '1.0';
    }
    
    return new Blob(
      [JSON.stringify(options.pretty ? data : options.output, null, options.pretty ? 2 : 0)], 
      { type: 'application/json;charset=utf-8' }
    );
  },

  async toCsv(rows: CsvRow[], headers?: string[]): Promise<Blob> {
    const allHeaders = headers || Array.from(new Set(rows.flatMap(row => Object.keys(row))));
    
    const csvLines = [
      allHeaders.join(','),
      ...rows.map(row => 
        allHeaders.map(header => {
          const value = row[header] ?? '';
          const stringValue = String(value);
          if (stringValue.includes(',') || stringValue.includes('"') || stringValue.includes('\n')) {
            return `"${stringValue.replace(/"/g, '""')}"`;
          }
          return stringValue;
        }).join(',')
      )
    ];
    
    return new Blob([csvLines.join('\n')], { type: 'text/csv;charset=utf-8' });
  },

  async toText(options: ExportOptions): Promise<Blob> {
    const { output, context, taskType, projectName, timestamp } = options;
    const date = timestamp || new Date();
    
    let text = `QA HELPER REPORT\n`;
    text += `${'='.repeat(50)}\n\n`;
    text += `Date: ${date.toLocaleString()}\n`;
    
    if (projectName) text += `Project: ${projectName}\n`;
    if (taskType) text += `Task Type: ${taskType}\n`;
    text += `\n${'─'.repeat(50)}\n\n`;
    
    if (context) {
      text += `CONTEXT:\n${context}\n\n`;
      text += `${'─'.repeat(50)}\n\n`;
    }
    
    text += `OUTPUT:\n${output}\n\n`;
    text += `${'─'.repeat(50)}\n`;
    text += `Generated by QA Copilot BY ssrjkk`;
    
    return new Blob([text], { type: 'text/plain;charset=utf-8' });
  },

  async downloadFile(blob: Blob, filename: string): Promise<void> {
    try {
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = filename;
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      URL.revokeObjectURL(url);
    } catch {
      const url = URL.createObjectURL(blob);
      window.open(url, '_blank');
      URL.revokeObjectURL(url);
    }
  },

  generateFilename(extension: string, taskType?: string): string {
    const date = new Date().toISOString().split('T')[0];
    const prefix = taskType ? `${taskType.replace(/[^a-z0-9]/gi, '-')}-${date}` : `qa-report-${date}`;
    return `${prefix}.${extension}`;
  },

  async exportAll(options: ExportOptions, formats: ('markdown' | 'pdf' | 'json' | 'csv' | 'text')[]): Promise<void> {
    const timestamp = options.timestamp || new Date();
    
    for (const format of formats) {
      let blob: Blob;
      let filename: string;
      
      switch (format) {
        case 'markdown':
          blob = await this.toMarkdown({ ...options, timestamp });
          filename = this.generateFilename('md', options.taskType);
          break;
        case 'pdf':
          blob = await this.toPdf({ ...options, timestamp });
          filename = this.generateFilename('pdf', options.taskType);
          break;
        case 'json':
          blob = await this.toJson({ ...options, timestamp, pretty: true, includeVersion: true });
          filename = this.generateFilename('json', options.taskType);
          break;
        case 'text':
          blob = await this.toText({ ...options, timestamp });
          filename = this.generateFilename('txt', options.taskType);
          break;
        case 'csv':
          blob = await this.toCsv([{ output: options.output, context: options.context, taskType: options.taskType }]);
          filename = this.generateFilename('csv', options.taskType);
          break;
        default:
          continue;
      }
      
      await this.downloadFile(blob, filename);
    }
  }
};
